# Site settings
baseurl = "https://chiaracorrado.dev" #without ending slash
# baseurl = "http://localhost:1313" #without ending slash
languageCode = "en-us"
title = "chiaracorrado.dev"
theme = "hugo-identity-theme"
#themesDir = "../.."

# Disable unnecessary kinds
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"]

# Enter your tracking code to enable Google Analytics
#googleAnalytics = "UA-XXXXX-Y"

[params]

  # Images settings
  # Icons, backgrounds and avatars folders are placed in theme's static/images folder.
  # You may place your images in corresponding folders and then set only filenames below to
  # change page's appearance

  # Site icons
  favicon_ico = "favicon.ico"
  favicon_ico_sizes = "16x16 32x32"
  appleicon = "apple.png"

  # Additional options to supplement icons served
  #favicon_png = "favicon.png"
  #favicon_png_sizes = "96x96"
  #favicon_svg = "favicon.svg"

  # Link custom assets relative to /static
  #custom_js  = [""]
  #custom_css = ["backgraound.css", "icons.css"]

  relativeURLs = true
  uglyURLs = true

  # Customization switches
  # Overwrite FontAwesome: see icons.css
  #custom_icons = true
  # Overwrite background: see background.css
  #custom_background = true

  # Personal data
  [params.personal]
    # If name is not set, author is used
    name = "Chiara Corrado"
    # Avatars can be written to images/avatars/
    avatar = "chiaracorrado.jpeg"
    position = "Software Architect"
    livesIn = "[Pisa, Italy](https://goo.gl/maps/23eCkWSmkW7BchnK8)"
    scope = [
        "[Women Techmaker Ambassador](https://www.womentechmakers.com/ambassadors/profiles/5f91b62008d3c01989865990/chiara_corrado)",
        "[GDG Pisa](http://gdgpisa.it/) Organizer",
        "[Debian](https://debian.org) & [Open Source](https://en.wikipedia.org/wiki/Open-source_model) Lover"
      ]
    biography = """Chiara is a software architect, a creative technologist and a dreamer. At 10 years old, she had her first computer with a 56k network card and 20GB of hard disk and she learned to use it and repair it by herself. She is currently making awesome things in an Italian SME. Chiara is enjoying coding in many program languages, but she is always focused to help others with her problem-solving capability. In her spare time, Chiara organizes events to support women in technology and she practices yoga, gardening, reading, cooking and try to live more ethically with the zero waste philosophy."""

  # Contact form settings

  [params.contact]
    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    email = "your@email.com"

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.

    #postURL = "https://example.com/mailout/"

    enable = false
    title = "Touch Me!"
    namePlaceholder = "Name"
    emailPlaceholder = "Email"
    messagePlaceholder = "Message"
    buttonText = "Send it"
    success = "Thank you for contacting us."
    error = "Message could not be send. Please contact us at "

    # Google invisible captcha
    #[params.contact.captcha]
    #  sitekey = ""


    # Add optional form fields to identify contact forms.
    #[[params.contact.fields.hidden]]
    #  name = "someID"
    #  value = "example.com"

    #[[params.contact.fields.hidden]]
    # Special values for name such as "page" and "site" will be autofilled
    #  name = "page"

  # Social settings
  # You may change these with your social links or add others

  [[params.social]]
    title = "Twitter"
    icon = "fa-twitter"
    link = "https://twitter.com/kiaruzza_dev"
    target = "_blank"

  [[params.social]]
    title = "Instagram"
    icon = "fa-instagram"
    link = "https://www.instagram.com/kiaruzza_dev/"
    target = "_blank"

  [[params.social]]
    title = "Linkedin"
    icon = "fa-linkedin"
    link = "https://www.linkedin.com/in/chiaracorrado/"
    target = "_blank"


  [[params.social]]
    title = "Facebook"
    icon = "fa-facebook"
    link = "https://www.facebook.com/chiara.corrado/"
    target = "_blank"

  [[params.social]]
    title = "Github"
    icon = "fa-github"
    link = "https://github.com/kiaruzza"
    target = "_blank"

  [[params.social]]
    title = "Medium"
    icon = "fa-medium"
    link = "https://medium.com/@kiaruzza_dev"
    target = "_blank"


  # Footer settings
  [params.footer]
    # If copyright is not set, author is used
    copyright = "Chiara Corrado"

  # Page license
  [params.license]
    link = "https://creativecommons.org/licenses/by-sa/4.0/legalcode"
    name = "CC-BY-SA-4.0"

  # Credits
  [[params.credits]]
    # Title is used as URL text
    title = "HTML5UP"
    # Text will be used to explain the credit
    text = "Design by"
    link = "https://html5up.net"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

